[TSK7-82] AI検診画面 コントローラー実装
unicorn-hal/unicorn-flutter pull request #132
Opened 2024-11-15 08:25 UTC by ishibashikeita

## 概要
・AI検診で使用するControllerとそれに伴うViewの修正
## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-11-15 17:12 UTC, kakeru-ikeda requested changes
レビュー完了しました👀
微修正と質問記載したのでご確認ください！

2024-11-15 17:12 UTC, kakeru-ikeda commented on lib/Controller/Chat/Ai/TextChat/ai_text_chat_controller.dart
> +  Future<void> postMessage([String? quickAction]) async {
ここの引数が[]で囲われる理由を教えていただけますか？

2024-11-15 17:12 UTC, kakeru-ikeda commented on lib/View/Chat/Ai/TextChat/ai_text_chat_view.dart
>  import 'package:unicorn_flutter/Service/Log/log_service.dart';
不要importの削除

2024-11-16 01:07 UTC, ishibashikeita commented on lib/Controller/Chat/Ai/TextChat/ai_text_chat_controller.dart
> +  Future<void> postMessage([String? quickAction]) async {
<img width="467" alt="スクリーンショット 2024-11-16 10 01 40" src="https://github.com/user-attachments/assets/5ba23340-58ef-40a1-92a3-1805ae79ad9d">
<img width="417" alt="スクリーンショット 2024-11-16 10 02 06" src="https://github.com/user-attachments/assets/6692169e-e913-4c40-a116-5d145a33688e">

postMessageをViewで呼び出すときに引数ごとなくせるみたいなことができるらしくてやってみた

2024-11-16 01:12 UTC, ishibashikeita commented on lib/Controller/Chat/Ai/TextChat/ai_text_chat_controller.dart
> +  Future<void> postMessage([String? quickAction]) async {
・基本postMessageには引数を渡さない(テキストフィールドのコントローラーの値を使う)
・クイックアクション時だけStringを渡したい

actionをnull許容Stringで定義して絶対渡すようにするよりもなんかきれいな気がして、、

2024-11-16 01:17 UTC, ishibashikeita commented on lib/Controller/Chat/Ai/TextChat/ai_text_chat_controller.dart
> +  //　チャット用のコントローラー
＼(^o^)／

2024-11-16 12:55 UTC, kakeru-ikeda commented on lib/Controller/Chat/Ai/TextChat/ai_text_chat_controller.dart
> +  Future<void> postMessage([String? quickAction]) async {
勉強になりました🙇‍♂️
多用していく

2024-11-16 12:55 UTC, kakeru-ikeda approved these changes
👍️

2024-11-16 12:55 UTC, merged