[TSK4-39][TSK4-40] normalHeakchCheckupとhealthCheckupResult 実装
unicorn-hal/unicorn-flutter pull request #141
Opened 2024-11-20 15:01 UTC by nolisio

## 概要
normalhealthCheckup VIew Controller
healthCheckupReqult View Controller 
各々に必要なデータ各位　追加
## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-11-22 07:43 UTC, ishibashikeita requested changes
先に修正おねがいします！

2024-11-22 07:43 UTC, ishibashikeita commented on lib/View/HealthCheckup/Results/health_checkup_results_view.dart
>                      },
ここ細かいけどControllerに移植しよう
viewからは病気名を渡してcontrollerの関数叩く形で👏

2024-11-22 07:43 UTC, ishibashikeita commented on lib/View/HealthCheckup/Results/health_checkup_results_view.dart
> +                                  builder: (context, snapshot) {
ユーザーネームはawaitしなくても取れます！
 UserData().user!.lastName;
 この形です！

2024-11-22 07:43 UTC, ishibashikeita commented on lib/View/HealthCheckup/Results/health_checkup_results_view.dart
> +                        )),
Viewに変更を加えた際はNotionなどにスクショを貼ってください！
次からでおｋ

2024-11-22 07:46 UTC, ishibashikeita commented on lib/Controller/HealthCheckup/health_checkup_result_controller.dart
> +    User? user = await UserApi().getUser(userId: AccountData().account!.uid);
ここ削除👏

2024-11-23 03:27 UTC, ishibashikeita requested changes
画面遷移機能の追加要望を記述しました！お願いします🙏

2024-11-23 03:27 UTC, ishibashikeita commented on lib/Controller/HealthCheckup/health_checkup_result_controller.dart
> +        DayOfWeekEnumType.toJapanseString(dayOfWeekEnum);
関数名を変更した意図はなんですか？
もとの関数名を他ファイルで使用しているため特に理由がなければ戻したい〜

2024-11-23 03:27 UTC, ishibashikeita commented on lib/View/HealthCheckup/Results/health_checkup_results_view.dart
>                                ),
言い忘れていたのですが、〇〇中Viewからcontext.goで遷移する(前の画面に戻さない)のでどこかに「検診トップに戻る」というボタンを設置してほしいです🙏

その際の繊維方法もcontext.goで遷移するように実装してください！
書き方は
` CheckupResultRoute().go(context);` みたいな感じ

わからなかったらきいてください！

2024-11-24 12:18 UTC, ishibashikeita approved these changes

2024-11-24 12:46 UTC, kakeru-ikeda commented on lib/Controller/HealthCheckup/health_checkup_result_controller.dart
> +  int healthPoint;
これらもfinal + Privateで宣言できます👀
コンストラクタでの宣言は`this._diseaseType`のような形でも受けられます

2024-11-26 05:01 UTC, kakeru-ikeda commented on lib/Constants/Enum/day_of_week_enum.dart
> +
なんですか、これ。

2024-11-26 15:20 UTC, kakeru-ikeda requested changes
よろしくお願いします！

2024-11-26 15:20 UTC, kakeru-ikeda commented on lib/Controller/HealthCheckup/Checkup/ai_checkup_controller.dart
> +    HealthCheckupDiseaseEnum diseaseType =
AIからの評価での値の揺れも実装しましょう👀

2024-11-26 15:20 UTC, kakeru-ikeda commented on lib/Constants/health_checkup_question.dart
ファイル名も複数形に

2024-11-26 15:20 UTC, kakeru-ikeda commented on lib/Constants/health_checkup_question.dart
> +  static List<HealthCheckupQuestion> questions = [
dataListに命名変更

2024-11-27 05:54 UTC, kakeru-ikeda approved these changes
OK👍️

2024-11-27 05:54 UTC, merged