[TSK3-14] Agoraビデオ通話の実装
unicorn-hal/unicorn-flutter pull request #150
Opened 2024-11-24 13:49 UTC by kakeru-ikeda

## 概要
Agoraを利用したビデオ通話の実装
デバッグ方法なども含めてNotionをご確認ください👀

## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-11-26 04:37 UTC, nolisio approved these changes

2024-11-26 06:34 UTC, ishibashikeita commented on lib/View/Chat/Doctor/VoiceCall/voice_call_view.dart
> +                    onTap: () => _onSwitchCamera(),
タッチ判定をもう少し大きくしてほしい！

2024-11-26 06:41 UTC, Rei0404nakada requested changes

2024-11-26 06:41 UTC, Rei0404nakada commented on lib/Controller/Chat/Doctor/VoiceCall/voice_call_controller.dart
> +  RtcEngine get engine => _engine;
getの位置をなおす

2024-11-26 06:41 UTC, Rei0404nakada commented on lib/Controller/Chat/Doctor/VoiceCall/voice_call_controller.dart
> +  void dispose() {
通話終了時にエラー出るんでなおしてね

2024-11-27 06:53 UTC, Rei0404nakada approved these changes

2024-11-27 06:58 UTC, ishibashikeita approved these changes
🔥

2024-11-27 07:10 UTC, nolisio approved these changes

2024-11-27 07:13 UTC, merged