[TSK7-103] 検診タブのリファクタ①
unicorn-hal/unicorn-flutter pull request #161
Opened 2024-12-01 08:34 UTC by ishibashikeita

## 概要
・検診タブにある不具合＆バグへの修正を行いました詳しくはNotionを見ればわかります

## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-12-01 13:02 UTC, kakeru-ikeda requested changes
レビュー行いました👀

2024-12-01 13:02 UTC, kakeru-ikeda commented on lib/View/HealthCheckup/health_checkup_top_view.dart
> +              ? Padding(
初回登録直後のユーザーでテストしましたが、検診終了後にTopに戻ってきても「今日の検診」の表示は切り替わらず、「過去の検診」にも追加されませんでした👀
一度再起動して、それぞれ表示がある状態で再検診を行うと値は変動していました。
こちらは即時性を持って表示をさせたいので修正をお願いします🙇‍♂️

2024-12-02 13:34 UTC, ishibashikeita commented on lib/Controller/HealthCheckup/Results/health_checkup_results_controller.dart
>          .launchUrl('https://ja.wikipedia.org/wiki/$diseaseName');
パッケージのcanlunchUrlが日本語を含むURLを絶対通さないマンだったのでServiceの方を修正しました🙏

2024-12-03 17:11 UTC, kakeru-ikeda approved these changes
こちらでも正常動作確認できました👍️

2024-12-03 17:11 UTC, kakeru-ikeda commented on lib/Service/Api/HealthCheckup/health_checkup_api.dart
> +      HealthCheckupCache().addData(HealthCheckup.fromJson(response.data));
いいね👀

2024-12-03 17:12 UTC, merged