[TSK7-112] かかりつけ医機能の実装
unicorn-hal/unicorn-flutter pull request #182
Opened 2024-12-14 03:30 UTC by ishibashikeita

## 概要
・かかりつけ医機能実装に伴うView/Controller/Serviceの修正を行いました。
・医師情報画面からかかりつけ医の登録・解除ができるように
・チャットTOP、医師情報画面、医師検索にバッジを追加
・top_loadingでかかりつけ医情報をgetしてcacheにいれるように

## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-12-14 03:41 UTC, ishibashikeita commented on lib/View/Component/Parts/user_info_tile.dart
> +                left: 10,
ここはれいくんの作業分をこちらでいれる

2024-12-14 09:51 UTC, kakeru-ikeda requested changes
修正お願いします👀

2024-12-14 09:51 UTC, kakeru-ikeda commented on lib/View/Component/Parts/user_info_tile.dart
> +    return Stack(
Rowでお願いします🙏

2024-12-14 09:51 UTC, kakeru-ikeda commented on lib/View/Chat/Doctor/Search/doctor_search_view.dart
> -                                  '病院: ${doctor.hospital.hospitalName} 診療科: ${doctor.departments.map((e) => e.departmentName).join(',')}',
ここ戻す

2024-12-14 09:51 UTC, kakeru-ikeda commented on lib/View/Chat/Doctor/Information/doctor_information_view.dart
> +                        text: '主治医解除',
三項演算子はフィールドレベルで行う👀

2024-12-14 09:51 UTC, kakeru-ikeda commented on lib/Controller/Chat/Doctor/Information/doctor_information_controller.dart
> +  Future<void> postPrimaryDoctors() async {
命名Doctorsから単数Doctorに変更
deleteも同様

2024-12-14 09:51 UTC, kakeru-ikeda commented on lib/Controller/Chat/Doctor/Information/doctor_information_controller.dart
> +  Future<void> deletePrimaryDoctors() async {
Protectorを含むAPI通信はtry catch finally を使うとより堅牢にできます👀

2024-12-15 05:01 UTC, kakeru-ikeda requested changes
微修正ですがよろしくお願いします🙏

2024-12-15 05:01 UTC, kakeru-ikeda commented on lib/View/Component/Parts/user_info_tile.dart
> +              Container(
元の実装の`right: 10`と同様になるようにPaddingを追加しましょう👀

2024-12-15 05:17 UTC, kakeru-ikeda approved these changes
👍️

2024-12-15 06:02 UTC, merged