[TSK5-18]View作成 - MyおくすりView
unicorn-hal/unicorn-flutter pull request #54
Opened 2024-10-25 09:00 UTC by Rei0404nakada

## 概要
MyおくすりViewとおくすり設定Viewの作成(モーダル、ドロップダウンボタン)

## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-10-25 10:07 UTC, kakeru-ikeda commented on lib/View/Profile/Medicine/medicine_view.dart
> +    List<Map<String, dynamic>> reminderList = [
本実装時はModelに起こす

2024-10-25 10:10 UTC, kakeru-ikeda commented on lib/View/Profile/Medicine/medicine_view.dart
> +                  color: Color.fromARGB(255, 149, 207, 255),
ここはAssetsに起こしましょう

2024-10-25 14:06 UTC, ishibashikeita requested changes
微修正お願いします！

2024-10-25 14:06 UTC, ishibashikeita commented on lib/View/Profile/Medicine/medicine_setting_view.dart
> +                                  hintText: '1 ~ 100(錠)',
![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-25 at 23 00 34](https://github.com/user-attachments/assets/d6c3a777-9773-4965-ae76-9679cc485e96)

もし最大容量が100錠なら3桁以上入力できちゃうのは親切じゃないかも、、、
めんどくさかったら自分がhotfix切るので言ってください

2024-10-25 14:06 UTC, ishibashikeita commented on lib/View/Profile/Medicine/medicine_setting_view.dart
> +                        ),
![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-25 at 23 02 19](https://github.com/user-attachments/assets/3a438e3b-937c-4c1d-8a04-460151e8e6bc)


下のものと同様で最大文字数を制限できたら親切かも、、、

2024-10-25 14:06 UTC, ishibashikeita commented on lib/View/Profile/Medicine/medicine_setting_view.dart
> +                                    showModalBottomSheet(
![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-25 at 23 03 23](https://github.com/user-attachments/assets/013ee309-d3ad-47c0-9b65-827b0a978e9b)

iOSでの見え方はこんな感じ！めちゃくちゃいいです👌

2024-10-25 14:06 UTC, ishibashikeita commented on lib/View/Profile/Medicine/medicine_setting_view.dart
> +                                ),
![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-25 at 23 03 33](https://github.com/user-attachments/assets/0f8045c0-f187-440e-8f9f-d8a50b9408ad)


繰り返し設定もいい感じですね👌

2024-10-25 17:51 UTC, Rei0404nakada commented on lib/View/Profile/Medicine/medicine_setting_view.dart
> +                                      ),
ドロップダウンボタンが画面右半分にあるのでしょうがないというか今の状態結構いいと思ってるので後で相談で

2024-10-25 17:57 UTC, Rei0404nakada commented on lib/View/Profile/Medicine/medicine_setting_view.dart
> +                                  hintText: '1 ~ 100(錠)',
CustomTextfieldのmaxLength引数で持てるように修正かけます。

2024-10-27 14:00 UTC, kakeru-ikeda approved these changes
OK👍️

2024-10-27 14:00 UTC, merged