[TSK7-9] homeに関わるコンポーネント①
unicorn-hal/unicorn-flutter pull request #6
Opened 2024-10-09 14:06 UTC by ishibashikeita

↑↑タイトルにNotionのカードIDを記載してください
ex.) [TSK1-1] hogeの追加

## 概要
homeに使用するコンポーネント2つ！

## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-10-09 15:53 UTC, Rei0404nakada approved these changes

2024-10-10 01:21 UTC, kakeru-ikeda requested changes
CircularProgressIndicatorをカスタムに起こしてください🙇‍♀

2024-10-10 01:21 UTC, kakeru-ikeda commented on lib/View/Component/Parts/Home/board_tile.dart
> +                          child: CircularProgressIndicator(
この先ローディングが増えそうな見込みがあるので、CircularProgressIndicatorもデザイン統一されたカスタム品を用意できますか？

2024-10-10 01:40 UTC, ishibashikeita commented on lib/View/Component/Parts/Home/board_tile.dart
> +                          child: CircularProgressIndicator(
画面全体のLoadingView的なものはれいくんに依頼してるので、今回みたいな画像の読み込みとかに使うindicatorだけの部品を作る対応で修正します！

2024-10-10 02:47 UTC, kakeru-ikeda approved these changes
ありがとう👍️

2024-10-10 02:48 UTC, merged