[TSK5-17]View作成 - 持病設定View
unicorn-hal/unicorn-flutter pull request #68
Opened 2024-10-28 12:05 UTC by Rei0404nakada

## 概要
持病表示・削除画面作成
持病検索・追加画面作成

## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-10-28 13:07 UTC, ishibashikeita requested changes
修正お願いします🙏

2024-10-28 13:07 UTC, ishibashikeita commented on lib/View/Profile/ChronicDisease/disease_search_view.dart
> +
　figmaにはなかったけどisEmptyの時、同じ高さのSizedBox・Centerで「🔍お悩みをさがす」みたいなあると優しいかも、色とかは任せる。いらなくね？ってなったら却下でもいいよー
![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-28 at 22 01 59](https://github.com/user-attachments/assets/d5165f60-de92-417e-a3e6-aa2b34c945f8)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-28 at 22 01 41](https://github.com/user-attachments/assets/43edf50c-add4-4a12-bcf2-41c6e5b9e9fc)

2024-10-28 13:07 UTC, ishibashikeita commented on lib/View/Profile/ChronicDisease/chronic_disease_view.dart
> +import 'package:flutter/material.dart';
iOSこんな感じです

![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-28 at 22 03 17](https://github.com/user-attachments/assets/f36ac27f-c642-42a9-963b-dbb3c955163c)

2024-10-28 13:07 UTC, ishibashikeita commented on lib/View/Profile/ChronicDisease/chronic_disease_view.dart
> +                                  bodyText: '本当に削除しますか？',
削除系で文言統一してStringsファイルに入れてくれると超嬉しい

2024-10-28 13:07 UTC, ishibashikeita commented on lib/View/Profile/ChronicDisease/disease_search_view.dart
> +                                      : () {
ここは常に決まった数表示したいはマジで同感です

2024-10-28 13:43 UTC, Rei0404nakada commented on lib/View/Profile/ChronicDisease/chronic_disease_view.dart
> +                                  bodyText: '本当に削除しますか？',
medicine_view.dartにも同じ修正あるのでIconButton直すときに一緒に直しときます

2024-10-28 13:51 UTC, ishibashikeita commented on lib/View/Profile/ChronicDisease/disease_search_view.dart
> +                      itemBuilder: (BuildContext context, int index) {
ここのリストビューはダブルスクロールになっちゃうのがUX的にダメということになったのでこのリストビューはスクロールしない方向で修正お願いします
昨日の案から変更してしまってすいません〜🙏

2024-10-28 14:15 UTC, Rei0404nakada commented on lib/View/Profile/ChronicDisease/disease_search_view.dart
> +                      itemBuilder: (BuildContext context, int index) {
これ相談で

2024-10-29 07:10 UTC, kakeru-ikeda approved these changes
👍️

2024-10-29 07:35 UTC, ishibashikeita approved these changes
🔥

2024-10-29 07:36 UTC, merged